apiVersion: v1
kind: ConfigMap
metadata:
  name: global-database-config
  namespace: default
data:
  database.url: "https://example.com:3306"
  
  # If using volumes, key is name of file, values are content
  database.properties: |
    DATABASE_URL="https://example.com:3306"